# -*- coding: utf-8 -*-
"""Python Assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lv29-biCWXxryKvbtC-nlrmsqtfrLFkf
"""

#PART 1 : UNDERSTANDING STRING LATERALS:
#SINGLE QUOTE:

print('hi! welcome to Python')

2. #Double Quote

print ("Hello World")

3. #Triple quote

print ("""Python, a language of clarity and power, empowered programmers to build anything, from simple scripts to complex applications, all with the graceful simplicity of a well-written poem""")

#STRING METHOD PRACTICE: PRINT NAME IN UPPER, LOWER AND FIRST LETTER OF EACH NAME CAPITALIZED
full_name= "Zara Asim"
print (full_name.upper())
print (full_name.lower())
print (full_name.title())

messy_text = "Python programming is fun!"
#REMOVE ALL EXTRA SPACES AT THEBEGINING AND END:
print(messy_text.strip())
#REPLACE "FUN" WITH "AMAZING"
print(messy_text.replace("fun","amazing"))

#split the sentence into a list of words:
sentence= "The baby cried over the toy which was broked by herself"
print(sentence.split())
#Join the words back together with dashes between them:
joined_sentence = "-".join( "The baby cried over the toy which was broked by herself".split())
print (joined_sentence)
#count how many times letter "i" appears in a sentence:
letter_to_count = "i"
count = sentence.count(letter_to_count)
print(f"The letter'{letter_to_count} appears {count}times in the sentence")
#check if the sentence starts with "The" :
if sentence.startswith("The"):
  print("The sentence starts with'The'")
else:
  print("The sentence does not starts with'The'")

#find the position of the word toy
print (sentence.find("toy"))

#F STRINGS
f"""
My name is {"Zara Asim"}
my age is {"28"}
I am a {"Student"}
I am currently in {"Quarter 3"}
I study in {"Governor House"}
We are studying {"Python"}
"""

#F STRINGS CREAING VARIABLES
My_name= "Zara Asim"
Age= "28"
Language= "Python"
Profession= "Student"
Location= "Governor House"

#USE F STRINGS IN A SENTENCE
f"""
My name is {My_name} and I am {Age} years old.
I enjoy programming in {Language} , its my favorite!.
I am a {Profession}
I study in {Location}
"""

#COMBINING STRING METHODS WITH F-STRINGS:

#user input
first_name = input("first_name")
last_name= input("last_name")
birth_year= input("birth_year")
#format the output to create a profile message.
"Profile:(first_name)(last_name) (birth_year)"
#COMBINING STRING METHODS WITH F-STRINGS:
"Profile:(first_name)(last_name) (birth_year)"
print(f"username: {first_name} {last_name} {birth_year}")

